FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
	DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 \
	POWERSHELL_TELEMETRY_OPTOUT=1

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        default-jdk \
        git \
        software-properties-common \
        wget \
    && wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y --no-install-recommends dotnet-sdk-8.0 dotnet-runtime-8.0 powershell \
    && curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64 \
    && chmod +x /usr/local/bin/opa \
    && curl -L -o /usr/local/bin/regal https://github.com/open-policy-agent/regal/releases/latest/download/regal_Linux_x86_64 \
    && chmod +x /usr/local/bin/regal \
    && curl -L -o /usr/local/bin/tla2tools.jar https://github.com/tlaplus/tlaplus/releases/latest/download/tla2tools.jar

WORKDIR /workspace

RUN dotnet --info && pwsh -c "$PSVersionTable" && opa version

CMD ["pwsh"]
